version: '3'

services:
  web-golf-ranking:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golf_ranking
    ports:
      - "3000:80"
      - "3000:443"
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs
