version: '3'

services:
  web-golf-ranking:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golf_ranking
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production 