# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Golf ranking

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Install PM2
        run: npm install pm2 -g

      - name: Start or restart PM2 process
        run: |
          # Kill the previous PM2 process, if any
          pm2 delete golf_ranking || true
          # Start the Next.js app with PM2
          pm2 start npm --name "golf_ranking" -- start
        working-directory: /var/www/golf_ranking_fe

      - name: Wait for PM2 to start
        run: pm2 logs golf_ranking --lines 100
